
functional:
  - Требование 3
  - Требование 4
  - Требование 9
  - Требование 8
non-functional:
  - Требование 1
  - Требование 7
  - Требование 2
  - Требование 10
implicit:
  - Требование 5
  - Требование 6
